### ISSUE TITLE
import dashboard from beats into kibana,can not find?

### ISSUE THREAD

**Issue by GounGG** [wtakase/kibana-own-home#155]
Import:
```yaml
setup.dashboards.kibana_index: .kibana_public
```
```shell
# metricbeat setup
Loaded index template
Loading dashboards (Kibana must be running and reachable)
Loaded dashboards
```

The log shows that the import was success，But if you switch to public tenant,still can't see it.

Ask for the correct import step

**Comment by WassimDhib** [comment]
Hi,

can you paste your kibana.yml config

**Comment by GounGG** [comment]
> 嗨，
> 
> 你可以粘贴你的kibana.yml配置

Ok,please check the configuration?
```yaml
server.host: "IP"
elasticsearch.url: "http://IP:19200"
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
own_home.session.secretkey: the-password-must-be-at-least-32-characters-long
own_home.session.isSecure: false
own_home.elasticsearch.url: http://IP:9200
```

**Comment by GounGG** [comment]
> Hi,
> 
> can you paste your kibana.yml config

Ok,please check the configuration?
```yaml
server.host: "IP"
elasticsearch.url: "http://IP:19200"
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie ]
own_home.session.secretkey: the-password-must-be-at-least-32-characters-long
own_home.session.isSecure: false
own_home.elasticsearch.url: http://IP:9200
```
