### ISSUE TITLE
Does own home support readonlyrest?

### ISSUE THREAD

**Issue by madhuakula** [wtakase/kibana-own-home#18]
Hello @wtakase 

Is there any way we can use own home integrated with readonlyrest similar to searchgaurd?

Thanks

**Comment by wtakase** [comment]
readonlyrest supports `proxy_auth` rule and we can use it. ([see this topic)](https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin/issues/193)

The followings are example of configurations:

httpd.conf:
```
RewriteEngine on
SSLProxyEngine on
RewriteRule  ^/?(.*)$ https://localhost:5601/$1 [L,P]
RequestHeader set X-Forwarded-User %{REMOTE_USER}s
<Location />
  SSLRequireSSL
  AuthType Basic
  AuthName "Basic Authentication"
  AuthUserFile /path/to/htpasswd
  Require valid-user
</Location>
```

kibana.yml:
```
elasticsearch.username: kibana
elasticsearch.password: kibana
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [ x-forwarded-user, cookie ]
own_home.proxy_user_header: x-forwarded-user
own_home.session.secretkey: the-password-must-be-at-least-32-characters-long
own_home.session.isSecure: false
own_home.local.groups: [ sandbox ]
```

elasticsearch.yml:
```
readonlyrest:
  enable: true
  response_if_req_forbidden: Sorry, your request is forbidden.
  access_control_rules:
  - name: "::KIBANA-SRV::"
    auth_key: kibana:kibana
    type: allow
  - name: access control for user01
    type: allow
    proxy_auth: ["user01"]
    indices: [".kibana_user01", ".kibana_sandbox", ".kibana-devnull"]
  - name: public search
    type: allow
    indices: ["public"]
    actions: ["indices:data/read/*"]
```
