### ISSUE TITLE
underscore in hostnames

### ISSUE THREAD

**Issue by ChristianKniep** [wtakase/kibana-own-home#23]
Hey there,

when using this within Docker SWARM as docker-service, the elasticsearch service will most likely include an underscore.
When I install your plugin, this leads to:

```
    "port": "9200",
     "host" [1]: "kibana_backend"
   }

   [1] "host" must be a valid hostname
```
It would be cool if you can somehow allow underscores - but I assume it is failing due to some dependency from 'the past'.

**Comment by wtakase** [comment]
I think this issue is out of scope of this plugin.

I'm not familiar with Docker SWARM.
But current docker does not allow underscore in hostname.
https://github.com/docker/docker/issues/22057

**Comment by ChristianKniep** [comment]
Sure, that might be an still open issue. But when you use Docker SWARM you will define a project name (`es`) and subservices of the `docker-compose` file will apear with an underscore...

```
cat docker-compose.yml                                                                                                                                                                                                                           git:(master|)
version: '3'
services:
  master:
    image: qnib/plain-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      resources:
        # Only one master for now
        replicas: 1
        limits:
          cpus: '1'
          memory: 768M
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: on-failure
    environment:
      ES_HEAP_MAX: "512m"
      ES_HEAP_MIN: "512m"
      ES_NODE_MASTER: "true"
      ES_NODE_DATA: "true"
```

```
$ docker stack deploy -c docker-compose.yml es 
Creating service es_master
$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                       PORTS               NAMES
0c0074f191a1        qnib/plain-elasticsearch:latest   "/usr/local/bin/en..."   About an hour ago   Up About an hour (healthy)                       es_master.1.swld84sfe75s71kdtirbqdxz6
```
So, when deploying using `docker stack deploy`, which I belive to be the suggested way, there are going to be underscores.

Maybe out of scope - I leave it for you to decide... :)
