### ISSUE TITLE
FATAL CLI ERROR YAMLException: can not read a block mapping entry;

### ISSUE THREAD

**Issue by joaoantoniopereira** [wtakase/kibana-own-home#40]
Hi,
In my kibana.yml I have:

own_home.proxy_user_header: x-proxy-user
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie, authorization ]
own_home.elasticsearch.url: localhost:9200
own_home.session.secretkey: the-password-must-be-at-least-32-characters-long
own_home.session.isSecure: false
own_home.local.groups: [ common01, common02 ]
elasticsearch.ssl.verify: false
own_home.get_username_from_session.enabled: true
own_home.get_username_from_session.key: username

when running kibana I get:

__________________________________________________________________________________________________
FATAL CLI ERROR YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 115, column 27:
    own_home.session.secretkey: the-password-must-be-at-least- ...
                              ^
    at generateError (/home/debian/Desktop/kibana-5.4.0-linux-x86_64/node_modules/js-yaml/lib/js-yaml/loader.js:160:10)
    at throwError (/home/debian/Desktop/kibana-5.4.0-linux-x86_64/node_modules/js-yaml/lib/js-yaml/loader.js:166:9)
    at readBlockMapping (/home/debian/Desktop/kibana-5.4.0-linux-x86_64/node_modules/js-yaml/lib/js-yaml/loader.js:1027:9)
    at composeNode (/home/debian/Desktop/kibana-5.4.0-linux-x86_64/node_modules/js-yaml/lib/js-yaml/loader.js:1315:12)
    at readDocument (/home/debian/Desktop/kibana-5.4.0-linux-x86_64/node_modules/js-yaml/lib/js-yaml/loader.js:1478:3)
    at loadDocuments (/home/debian/Desktop/kibana-5.4.0-linux-x86_64/node_modules/js-yaml/lib/js-yaml/loader.js:1538:5)
    at load (/home/debian/Desktop/kibana-5.4.0-linux-x86_64/node_modules/js-yaml/lib/js-yaml/loader.js:1555:19)
    at safeLoad (/home/debian/Desktop/kibana-5.4.0-linux-x86_64/node_modules/js-yaml/lib/js-yaml/loader.js:1573:10)
    at files.map.path (/home/debian/Desktop/kibana-5.4.0-linux-x86_64/src/cli/serve/read_yaml_config.js:10:56)
    at Array.map (native)
__________________________________________________________________________________________

When I comment the line own_home.elasticsearch.url: localhost:9200, kibana initializes but I get
log [16:54:10.932] [error][status][ui settings] Status changed from uninitialized to red - Elasticsearch plugin is red

Does anyone know what is the problem here? I do not have tabs on my config file..
Thanks!

**Comment by wtakase** [comment]
Could you try to replace `own_home.elasticsearch.url: localhost:9200` with `own_home.elasticsearch.url: http://localhost:9200`?

And if you use `own_home.get_username_from_session` options, you need to set up an application to authenticate user such as [search-guard-kibana-plugin](https://github.com/floragunncom/search-guard-kibana-plugin).

**Comment by joaoantoniopereira** [comment]
Replacing with http://.. gives the same result.
Yes I have searchguard running also

**Comment by wtakase** [comment]
In my environment it seems to work well:

- kibana 5.4.0
- elasticsearch 5.4.0
- searchguard 5.4.0-12
- searchguard kibana plugin 5.4.0-2 
- own home 5.4.0

elasticsearch.yml:
```
searchguard.ssl.transport.keystore_filepath: keystore.jks
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: false
searchguard.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test, C=de
cluster.name: searchguard_demo
network.host: 0.0.0.0
```

sg_config.yml:
```
searchguard:
  dynamic:
    authc:
      basic_internal_auth_domain: 
        enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
```

add the following lines to sg_action_groups.yml:
```
KIBANA_READ:
  - READ
  - "indices:admin/mappings/fields/get*"
  - "indices:admin/validate/query*"
  - "indices:admin/get*"
```

sg_internal_users.yml:
```
admin:
  hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
kibanaserver:
  hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
user01:
  hash: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

sg_roles.yml:
```
sg_all_access:
  cluster:
    - '*'
  indices:
    '*':
      '*':
        - '*'

sg_kibana_server:
  cluster:
      - CLUSTER_MONITOR
      - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana*':
      '*':
        - ALL

sg_kibana_user:
  cluster:
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana':
      '*':
        - ALL
    '?kibana-devnull':
      '*':
        - KIBANA_READ

sg_own_kibana_index:
  cluster:
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana_${user_name}':
      '*':
        - ALL
    '?kibana-devnull':
      '*':
        - KIBANA_READ

sg_public_kibana_index:
  cluster:
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana_public':
      '*':
        - ALL
    '?kibana-devnull':
      '*':
        - KIBANA_READ

sg_some_index:
  cluster:
    - CLUSTER_COMPOSITE_OPS
  indices:
    'someindex-*':
      '*':
        - KIBANA_READ
```

sg_roles_mapping.yml:
```
sg_all_access:
  users:
    - admin

sg_kibana_server:
  users:
    - kibanaserver

sg_kibana_user:
  users:
    - '*'

sg_own_kibana_index:
  users:
    - '*'

sg_public_kibana_index:
  users:
    - '*'

sg_some_index:
  users:
    - '*'
```

kibana.yml:
```
server.defaultRoute: /app/own_home
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [ cookie, authorization ]
elasticsearch.username: "kibanaserver"
elasticsearch.password: "xxxxxxxxxxxx"
own_home.get_username_from_session.enabled: true
own_home.get_username_from_session.key: username
own_home.session.isSecure: false
own_home.elasticsearch.url: http://localhost:9200
own_home.session.secretkey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
own_home.local.groups: [ public ]
searchguard.cookie.secure: false
searchguard.cookie.password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

In kibana/plugins/searchguard/lib/backend/searchguard_plugin.js,
replace `_searchguard/authinfo` with `/_searchguard/authinfo`, and
replace `_searchguard/kibanainfo` with `/_searchguard/kibanainfo`.

access http://localhost:5601
