### ISSUE TITLE
Kibana settings not being saved

### ISSUE THREAD

**Issue by fbrcosta** [wtakase/kibana-own-home#51]
Hello,

I'm having an issue trying to save some settings in Advanced Settings. It looks like the these settings that are made through the api (/api/kibana/settings) are saved only for that session. Every time I click in the Own Home Tab or I log in again, the settings disappear. It's pretty annoying cause every time I log in I have to choose the default index, set the settings again, since I'm using x-pack, i have the welcome message from x-pack, ...
Has anyone encountered the same issue? 

I'm using kibana (and elasticsearch) 5.5.0, I'm also using search guard 5. my kibana.yml looks like this:
````
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"
xpack.graph.enabled: false # elastic and kibana
xpack.ml.enabled: false # elastic and kibana
xpack.monitoring.enabled: true # elastic and kibana
xpack.reporting.enabled: false # kibana only
xpack.security.enabled: false # elastic and kibana
xpack.monitoring.elasticsearch.url: "http://localhost:9202"
searchguard.cookie.password: <SECRET>
searchguard.cookie.secure: false
elasticsearch.url: http://localhost:19200
elasticsearch.ssl.verify: false
elasticsearch.requestHeadersWhitelist:
 - cookie
 - authorization
own_home.elasticsearch.url: http://localhost:9200
own_home.get_username_from_session.enabled: true
own_home.get_username_from_session.key: username
own_home.session.isSecure: false
own_home.session.secretkey: <SECRET>
own_home.local.enabled: true
own_home.local.groups: [ public01, public02, public03 ]
server.defaultRoute: /app/own_home
````

**Comment by wtakase** [comment]
Own home has not been tested with x-pack.

I tested on the following environment (without x-pack) and it worked fine:

Elasticsearch: 5.5.1
Search Guard: 5.5.1-14
Kibana: 5.5.1
Own Home: 5.5.1
Search Guard Kibana plugin: 5.5.1-3


elasticsearch.yml:
```
searchguard.ssl.transport.keystore_filepath: keystore.jks
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: false
searchguard.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test, C=de

cluster.name: searchguard_demo
network.host: 0.0.0.0
```

add the following lines to sg_action_groups.yml:
```
KIBANA_READ:
  - READ
  - "indices:admin/mappings/fields/get*"
  - "indices:admin/validate/query*"
  - "indices:admin/get*"
```

sg_config.yml:
```
searchguard:
  dynamic:
    authc:
      basic_internal_auth_domain: 
        enabled: true
        order: 0
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
```

sg_roles.yml:
```
sg_admin:
  cluster:
    - UNLIMITED
  indices:
    '*':
      '*':
        - UNLIMITED

sg_kibana_server:
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana*':
      '*':
        - INDICES_ALL

sg_kibana_user:
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    '?kibana':
      '*':
        - INDICES_ALL
    '?kibana-devnull':
      '*':
        - KIBANA_READ

sg_own_kibana_index:
  cluster:
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana_${user_name}':
      '*':
        - INDICES_ALL
    '?kibana-devnull':
      '*':
        - KIBANA_READ

sg_public_kibana_index:
  cluster:
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana_public':
      '*':
        - INDICES_ALL
    '?kibana-devnull':
      '*':
        - KIBANA_READ

sg_example_index:
  indices:
    'example-*':
      '*':
        - READ
```

sg_roles_mapping.yml:
```
sg_admin:
  users:
    - admin

sg_kibana_server:
  users:
    - kibanaserver

sg_kibana_user:
  users:
    - '*'

sg_own_kibana_index:
  users:
    - '*'

sg_public_kibana_index:
  users:
    - '*'

sg_example_index:
  users:
    - '*'
```

sg_internal_users.yml:
```
admin:
  hash: $2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG
  #password is: admin
kibanaserver:
  hash: $2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H.
  #password is: kibanaserver
test:
  hash: $2a$12$1HqHxm3QTfzwkse7vwzhFOV4gDv787cZ8BwmCwNEyJhn0CZoo8VVu
  #password is: test
```

kibana.yml:
```
server.defaultRoute: /app/own_home
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [ cookie, authorization ]
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
elasticsearch.ssl.verify: false
own_home.get_username_from_session.enabled: true
own_home.get_username_from_session.key: username
own_home.session.isSecure: false
own_home.elasticsearch.url: http://localhost:9200
own_home.session.secretkey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
own_home.local.groups: [ public ]
searchguard.cookie.secure: false
searchguard.cookie.password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

![issue51](https://user-images.githubusercontent.com/8382795/28853880-7ca6212e-776e-11e7-8a37-e867ac1d931d.gif)
