### ISSUE TITLE
Internal server error after upgrading to 5.6.2

### ISSUE THREAD

**Issue by spokky** [wtakase/kibana-own-home#54]
Hi,
I've just upgraded from 5.4.2 to 5.6.4. I'm also using searchguard. Everything works fine but not after the installation of own_home. When I'm trying to configure the index pattern this is the error that appears:

`Error: An internal server error occurred
    at http://qcmi03.inetworking.it/bundles/kibana.bundle.js?v=15543:212:27693
    at processQueue (http://qcmi03.inetworking.it/bundles/commons.bundle.js?v=15543:38:23621)
    at http://qcmi03.inetworking.it/bundles/commons.bundle.js?v=15543:38:23888
    at Scope.$eval (http://qcmi03.inetworking.it/bundles/commons.bundle.js?v=15543:39:4619)
    at Scope.$digest (http://qcmi03.inetworking.it/bundles/commons.bundle.js?v=15543:39:2359)
    at Scope.$apply (http://qcmi03.inetworking.it/bundles/commons.bundle.js?v=15543:39:5037)
    at done (http://qcmi03.inetworking.it/bundles/commons.bundle.js?v=15543:37:25027)
    at completeRequest (http://qcmi03.inetworking.it/bundles/commons.bundle.js?v=15543:37:28702)
    at XMLHttpRequest.xhr.onload (http://qcmi03.inetworking.it/bundles/commons.bundle.js?v=15543:37:29634)`

If I insert the index name it can't find the time filter (and I cannot create the index).
This is the kibana log:

`{"type":"error","@timestamp":"2017-10-05T14:46:30Z","tags":[],"pid":27477,"level":"error","message":"Cannot convert undefined or null to object","error":{"message":"Cannot convert undefined or null to object","name":"TypeError","stack":"TypeError: Cannot convert undefined or null to object\n    at readFieldCapsResponse (/usr/share/kibana/src/server/index_patterns/service/lib/field_capabilities/field_caps_response.js:75:17)\n    at /usr/share/kibana/src/server/index_patterns/service/lib/field_capabilities/field_capabilities.js:20:107\n    at next (native)\n    at step (/usr/share/kibana/src/server/index_patterns/service/lib/field_capabilities/field_capabilities.js:50:191)\n    at /usr/share/kibana/src/server/index_patterns/service/lib/field_capabilities/field_capabilities.js:50:361"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"?pattern=logstash&meta_fields=%5B%22_source%22%2C%22_id%22%2C%22_type%22%2C%22_index%22%2C%22_score%22%5D","query":{"pattern":"logstash","meta_fields":"[\"_source\",\"_id\",\"_type\",\"_index\",\"_score\"]"},"pathname":"/api/index_patterns/_fields_for_wildcard","path":"/api/index_patterns/_fields_for_wildcard?pattern=logstash&meta_fields=%5B%22_source%22%2C%22_id%22%2C%22_type%22%2C%22_index%22%2C%22_score%22%5D","href":"/api/index_patterns/_fields_for_wildcard?pattern=logstash&meta_fields=%5B%22_source%22%2C%22_id%22%2C%22_type%22%2C%22_index%22%2C%22_score%22%5D"}}
{"type":"response","@timestamp":"2017-10-05T14:46:30Z","tags":[],"pid":27477,"method":"get","statusCode":500,"req":{"url":"/api/index_patterns/_fields_for_wildcard?pattern=logstash&meta_fields=_source&meta_fields=_id&meta_fields=_type&meta_fields=_index&meta_fields=_score","method":"get","headers":{"x-proxy-user":"intesys","host":"localhost:5601","connection":"close","accept":"application/json, text/plain, */*","kbn-version":"5.6.2","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36","referer":"http://qcmi03.inetworking.it/app/kibana","accept-encoding":"gzip, deflate","accept-language":"it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"http://qcmi03.inetworking.it/app/kibana"},"res":{"statusCode":500,"responseTime":10,"contentLength":9},"message":"GET /api/index_patterns/_fields_for_wildcard?pattern=logstash&meta_fields=_source&meta_fields=_id&meta_fields=_type&meta_fields=_index&meta_fields=_score 500 10ms - 9.0B"}
`

Any ideas?

thanks

**Comment by angad** [comment]
Exact same issue. Using with search guard. v5.6.2 everything.

**Comment by wtakase** [comment]
Sorry for the delay. I will have a look.

**Comment by angad** [comment]
I fixed it by adding elasticsearch.customHeaders: {authorization: "Basic <<auth>>"} to my kibana config.
For some reason, own home is not sending the auth headers for POST requests.

**Comment by spokky** [comment]
I've added the custom header but still not working. These are the confs:

/usr/share/elasticsearch/plugins/search-guard-5/sgconfig/sg_roles.yml
`sg_all_access:
  cluster:
    - '*'
  indices:
    '*':
      '*':
        - '*'

sg_kibana_server:
  cluster:
      - CLUSTER_MONITOR
      - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana*':
      '*':
        - ALL

sg_logstash:
  cluster:
    - indices:admin/template/get
    - indices:admin/template/put
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    '*':
      '*':
        - CRUD
        - CREATE_INDEX

sg_kibana_user:
  cluster:
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana':
      '*':
        - ALL
    '?kibana-devnull':
      '*':
        - KIBANA_READ

sg_own_kibana_index:
  cluster:
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana_${user_name}':
      '*':
        - ALL
    '?kibana-devnull':
      '*':
        - KIBANA_READ

sg_kibana_inetworking:
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    'system_auth-xxxxxx-*':
      '*':
        - ALL

sg_kibana_intesys:
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    'system_auth-xxxxx-*':
      '*':
        - ALL

sg_kibana_barracuda:
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    'barracuda_mail_xxxxxxx-*':
      '*':
        - ALL
`
kibana.yml

`server.port: 5601
server.host: "localhost"
server.name: "host.name"
elasticsearch.url: "http://localhost:19200"
#elasticsearch.url: "http://localhost:9200"
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie, ]
elasticsearch.customHeaders: {authorization: "Basic <>"}
elasticsearch.username: "kibanaserver"
elasticsearch.password: "kibanaserver"
console.enabled: false
timelion.enabled: false
own_home.local.enabled: false
own_home.session.isSecure: false
own_home.session.secretkey: **************************************
own_home.elasticsearch.url: http://127.0.0.1:9200
own_home.proxy_user_header: x-proxy-user
elasticsearch.preserveHost: true
#kibana.index: ".kibana"
logging.dest: /var/log/kibana.log
logging.silent: false
#logging.quiet: false
logging.verbose: true
i18n.defaultLocale: "it"
`
elasticsearch.yml

`cluster.name: ****************
node.name: host.name
network.host: localhost
bootstrap.memory_lock: true
node.master: 1
node.data: 1
transport.tcp.port: 9300
http.port: 9200
discovery.zen.ping.unicast.hosts: ["192.168.170.13"]
searchguard.ssl.transport.keystore_filepath: CN=******************-keystore.jks
searchguard.ssl.transport.keystore_password: ******************
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: ******************
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: false
searchguard.ssl.http.keystore_filepath: CN=******************-keystore.jks
searchguard.ssl.http.keystore_password: ******************
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: ******************
                                                             
searchguard.authcz.admin_dn:                                
  - CN=sgadmin
`

**Comment by wtakase** [comment]
I assume you have a proxy server in front of kibana, and don't use searchguard kibana plugin.
I confirmed that `test` user could create `example-*` index pattern as follows settings:

httpd.conf (snipped)
```
RewriteEngine on
RewriteRule  ^/?(.*)$ http://localhost:5601/$1 [L,P]
RequestHeader set X-Proxy-User expr=%{REMOTE_USER}
<Location />
  AuthType Basic
  AuthName "Basic Authentication"
  AuthUserFile /path/to/.htpasswd  # contains `test` user
  Require valid-user
</Location>
```

kibana.yml
```
elasticsearch.url: http://localhost:19200
elasticsearch.requestHeadersWhitelist: [ cookie, x-proxy-user ]
own_home.elasticsearch.url: http://localhost:9200
own_home.session.isSecure: false
own_home.local.enabled: false
elasticsearch.username: kibanaserver
elasticsearch.password: kibanaserver
```

elasticsearch.yml
```
searchguard.ssl.transport.keystore_filepath: keystore.jks
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.enabled: false
searchguard.authcz.admin_dn:
  - CN=kirk,OU=client,O=client,L=test, C=de
cluster.name: searchguard_demo
network.host: 0.0.0.0
```

sg_config.yml
```
searchguard:
  dynamic:
    authc:
      proxy_auth_domain:
        enabled: true
        order: 0
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: "x-proxy-user"
        authentication_backend:
          type: noop
      basic_internal_auth_domain: 
        enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
```

sg_internal_users.yml
```
admin:
  hash: $2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG
  #password is: admin
kibanaserver:
  hash: $2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H.
  #password is: kibanaserver
```

sg_action_groups.yml (add the following lines)
```
KIBANA_READ:
  - READ
  - "indices:admin/mappings/fields/get*"
  - "indices:admin/validate/query*"
  - "indices:admin/get*"
```

sg_roles.yml
```
sg_admin:
  cluster:
    - UNLIMITED
  indices:
    '*':
      '*':
        - UNLIMITED

sg_kibana_server:
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana*':
      '*':
        - INDICES_ALL

sg_own_kibana_index:
  cluster:
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana_${user_name}':
      '*':
        - INDICES_ALL
    '?kibana-devnull':
      '*':
        - KIBANA_READ

sg_example_index:
  indices:
    'example-*':
      '*':
        - READ
```

sg_roles_mapping.yml
```
sg_admin:
  users:
    - admin

sg_kibana_server:
  users:
    - kibanaserver

sg_own_kibana_index:
  users:
    - '*'

sg_example_index:
  users:
    - '*'
```
