### ISSUE TITLE
path must be a string or Buffer

### ISSUE THREAD

**Issue by johnseekins** [wtakase/kibana-own-home#55]
I receive this error on Kibana 5.6.2 (with own-home 5.6.2 installed) _even_ if the `own-home` section of the config is completely removed:

```
{"type":"log","@timestamp":"2017-10-12T17:11:26Z","tags":["fatal"],"pid":12203,"level":"fatal","message":"path must be a string or Buffer","error":{"message":"path must be a string or Buffer","name":"TypeError","stack":"TypeError: path must be a string or Buffer\n    at TypeError (native)\n    at Object.fs.openSync (fs.js:641:18)\n    at fs.readFileSync (fs.js:509:33)\n    at module.exports (/usr/share/kibana/plugins/own_home/server/proxy/init_proxy.js:33:14)\n    at ScopedPlugin.init [as externalInit] (/usr/share/kibana/plugins/own_home/index.js:86:9)\n    at ScopedPlugin.tryCatcher (/usr/share/kibana/node_modules/bluebird/js/main/util.js:26:23)\n    at Promise.attempt.Promise.try (/usr/share/kibana/node_modules/bluebird/js/main/method.js:30:24)\n    at /usr/share/kibana/src/server/plugins/plugin.js:177:46\n    at next (native)\n    at step (/usr/share/kibana/src/server/plugins/plugin.js:21:191)\n    at /usr/share/kibana/src/server/plugins/plugin.js:21:361"}}
```

My config file:
```
server:
  host: 0.0.0.0
  name: <kibana hostname>
  ssl:
    enabled: true
    key: /usr/share/kibana/config/kibana.key
    certificate: /usr/share/kibana/config/kibana.crt

elasticsearch:
  url: https://<elasticsearch hostname>:9200
  username: dm_es_cli
  password: F34icfRem7my7cSXthSd
  ssl:
    certificateAuthorities: ["...cert"]
  requestHeadersWhitelist: [ x-proxy-user, cookie ]
```

**Comment by johnseekins** [comment]
Turns out I had some permission problems (beyond just own_home) that were causing kibana to break. Fixing those got me further down the path...

Now if you can make the error more clear...that would be awesome.

Here's logtrail failing for the same reason:
```
{"type":"log","@timestamp":"2017-10-12T18:29:23Z","tags":["fatal"],"pid":12938,"level":"fatal","message":"EACCES: permission denied, open '/usr/share/kibana/optimize/bundles/logtrail.entry.js'","error":{"message":"EACCES: permission denied, open '/usr/share/kibana/optimize/bundles/lo
gtrail.entry.js'","name":"Error","stack":"Error: EACCES: permission denied, open '/usr/share/kibana/optimize/bundles/logtrail.entry.js'\n    at Error (native)","code":"EACCES"}}   
```

**Comment by johnseekins** [comment]
Once I got there, I had to test config items within own_home until I found which configs needed to be what...your docs on config settings aren't _exactly_ right, but they're fairly close...

My final config:
```
server:
  host: 0.0.0.0
  port: 5601
  name: <kibana hostname>
  ssl:
    enabled: true
    key: /usr/share/kibana/config/kibana.key
    certificate: /usr/share/kibana/config/kibana.crt

elasticsearch:
  url: <elasticsearch hostname>
  username: <user>
  password: <password>
  ssl:
    certificateAuthorities: ["....cert"]
  requestHeadersWhitelist: [ x-proxy-user, cookie ]

own_home:
  local:
    enabled: false
  elasticsearch:
    url: <elasticsearch host>
    ssl:
      certificateAuthorities: ["...cert"]
  proxy_user_header: x-proxy-user
  session:
    isSecure: true
    secretkey: '<shhh...>'
  ldap:
    enabled: true
    url: "<ldap host>"
    userbase: "<user search>"
    rolebase: "<group search>"
    search_filter: '(cn=es_*)'
    username_attribute: cn
    rolename_attribute: cn
    member_attribute: member
    get_dn_dynamically: true
```
