### ISSUE TITLE
SearchGuard with nginx-ldap module

### ISSUE THREAD

**Issue by davtex** [wtakase/kibana-own-home#61]
Hi,

I am trying to get the following to work:

Setup:
ElasticSearch 5.6.3 cluster with SearchGuard 5.6.3 installed with basic-auth enabled.
Kibana 5.6.3 with OwnHome 5.6.3
nginX with LDAP module

Idea:
Use SG's basic auth for admin/logstash/kibana access to Elastic
Use LDAP auth for user access to Kibana (by using nginx-auth-ldap)

Problem:
User index cannot be created, Kibana cannot see any indexes during "Configure an index pattern" and Kibana throws
` error  [10:08:07.259]  TypeError: Cannot convert undefined or null to object
    at readFieldCapsResponse (/usr/share/kibana/src/server/index_patterns/service/lib/field_capabilities/field_caps_response.js:75:17)
    at /usr/share/kibana/src/server/index_patterns/service/lib/field_capabilities/field_capabilities.js:20:107
    at next (native)
    at step (/usr/share/kibana/src/server/index_patterns/service/lib/field_capabilities/field_capabilities.js:50:191)
    at /usr/share/kibana/src/server/index_patterns/service/lib/field_capabilities/field_capabilities.js:50:361
`

For testing puproses, I am not using LDAP but basic auth on nginx reverse proxy. **The problem disappears when the same user:password is configured in both nginx and SG.**

My thinking is that due to your integration with SG, credentials from nginx are being forwarded to SG, which is not desired in my case. 

Question:
Can I somehow force Kibana/Own Home to use "elasticsearch.username" and "elasticsearch.password" all the time?

**Comment by wtakase** [comment]
could you show your nginx conf (basic auth and ldap auth), kibana.yml, sg_config.yml, sg_roles.yml, and sg_roles_mapping.yml?

**Comment by davtex** [comment]
Just to add, the following error appear before the one I mentioned earlier. I am using david:admin on nginx, passing "david" in request header. Problem disappears when I add david:admin to SG.

```
Unhandled rejection Authentication Exception :: {"path":"/.kibana_david","query":{},"statusCode":401,"response":"","wwwAuthenticateDirective":"Basic realm=\"Search Guard\""}
    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:295:15)
    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:254:7)
    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
    at IncomingMessage.bound (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Nginx:
```
  location /kibana/ {

      auth_basic           "Administrator’s Area";
      auth_basic_user_file /etc/nginx/.htpasswd;

#      auth_ldap "Enter Credentials: ";
#      auth_ldap_servers ad_groups;
      proxy_set_header X-PROXY-USER $remote_user;

      proxy_set_header    Host $host;
      proxy_set_header    X-Real-IP $remote_addr;
      proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header    X-Forwarded-Proto $scheme;

      proxy_pass          http://localhost:5601/;
      proxy_read_timeout  90;

      proxy_redirect      http://localhost:5601 https://XYZ.com/kibana/;

    }
```

Kibana:
```
elasticsearch.password: "kibanaserver"
elasticsearch.requestHeadersWhitelist: [ x-proxy-user, cookie, authorization]
elasticsearch.ssl.verificationMode: none
elasticsearch.ssl.verify: false
elasticsearch.url: http://127.0.0.1:19200
elasticsearch.username: "kibanaserver"
own_home.elasticsearch.url: https://localhost:9200
own_home.session.isSecure: false
own_home.session.secretkey: nqJa2Gb095XCpOfaUpzokEvJbAR0vndd
server.basePath: "/kibana"
server.defaultRoute: /app/own_home
server.host: "127.0.0.1"
server.port: 5601
```

sg_config (default, I did no editing):
```
searchguard:
  dynamic:
    kibana:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        remoteIpHeader:  'x-forwarded-for'
        proxiesHeader:   'x-forwarded-by'
    authc:
      kerberos_auth_domain:
        enabled: false
        order: 6
        http_authenticator:
          challenge: true
          config:
            krb_debug: false
            strip_realm_from_principal: true
        authentication_backend:
          type: noop
      basic_internal_auth_domain:
        enabled: true
        order: 4
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: intern
      proxy_auth_domain:
        enabled: false
        order: 3
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: "x-proxy-user"
            roles_header: "x-proxy-roles"
        authentication_backend:
          type: noop
      host_auth_domain:
        enabled: false
        order: 1
        http_authenticator:
          challenge: false
        authentication_backend:
          type: noop
      jwt_auth_domain:
        enabled: false
        order: 0
        http_authenticator:
          type: jwt
          challenge: false
          config:
            signing_key: "base64 encoded key"
            jwt_header: "Authorization"
            jwt_url_parameter: null
            roles_key: null
            subject_key: null
        authentication_backend:
          type: noop
      clientcert_auth_domain:
        enabled: false
        order: 2
        http_authenticator:
          type: clientcert
          config:
          challenge: false
        authentication_backend:
          type: noop
      ldap:
        enabled: false
        order: 5
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          config:
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: true
            hosts:
              - localhost:8389
            bind_dn: null
            password: null
            userbase: 'ou=people,dc=example,dc=com'
            usersearch: '(sAMAccountName={0})'
            username_attribute: null
    authz:
      roles_from_myldap:
        enabled: false
        authorization_backend:
          config:
            enable_ssl: false
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: true
            hosts:
              - localhost:8389
            bind_dn: null
            password: null
            rolebase: 'ou=groups,dc=example,dc=com'
            rolesearch: '(member={0})'
            userroleattribute: null
            userrolename: disabled
            rolename: cn
            resolve_nested_roles: true
            userbase: 'ou=people,dc=example,dc=com'
            usersearch: '(uid={0})'
      roles_from_another_ldap:
        enabled: false
        authorization_backend:
```

sg_roles (default, no editing):
```
#<sg_role_name>:
#  cluster:
#    - '<permission>'
#  indices:
#    '<indexname or alias>':
#      '<type>':
#        - '<permission>'
#      _dls_: '<querydsl query>'
#      _fls_:
#        - '<field>'
#        - '<field>'

# When a user make a request to elasticsearch then the following roles will be evaluated to see if the user has
# permissions for the request. A request is always associated with an action and is executed against and index (or alias)
# and a type. If a request is executed against all indices (or all types) then the asterix ('*') is needed.
# Every role a user has will be examined if it allows the action against an index (or type). At least one role must match
# for the request to be successful. If no role match then the request will be denied. Currently a match must happen within
# one single role - that means that permissions can not span multiple roles.

# For <permission>, <indexname or alias> and <type> simple wildcards and regular expressions are possible.
# A asterix (*) will match any character sequence (or an empty sequence)
# A question mark (?) will match any single character (but NOT empty character)
# Example: '*my*index' will match 'my_first_index' as well as 'myindex' but not 'myindex1'
# Example: '?kibana' will match '.kibana' but not 'kibana'

# To use a full blown regex you have to pre- and apend a '/' to use regex instead of simple wildcards
# '/<java regex>/'
# Example: '/\S*/' will match any non whitespace characters

# Important:
# Index, alias or type names can not contain dots (.) in the <indexname or alias> or <type> expression.
# Reason is that we currently parse the config file into a elasticsearch settings object which cannot cope with dots in keys.
# Workaround: Just configure something like '?kibana' instead of '.kibana' or 'my?index' instead of 'my.index'
# This limitation will likely removed with Search Guard 6

# DLS (Document level security) - NOT FREE FOR COMMERCIAL
# Install https://github.com/floragunncom/search-guard-module-dlsfls
# Per Index you can define a DLS query
# If more than one DLS query match they will be OR'ed

# FLS (Field level security) - NOT FREE FOR COMMERCIAL
# Per Index you can define a FLS fields
# If more than one FLS config match the field will be appended
# Install https://github.com/floragunncom/search-guard-module-dlsfls

# Kibana multitenancy - NOT FREE FOR COMMERCIAL
# Per role you can define on ore more tenants
# https://github.com/floragunncom/search-guard-docs/blob/master/multitenancy.md

# Default role for all users (including anonymous)
sg_public:
  cluster:
    - cluster:monitor/main
    - CLUSTER_COMPOSITE_OPS_RO

# Allows everything
# but not changes to searchguard config/index
sg_all_access:
  cluster:
    - UNLIMITED
  indices:
    '*':
      '*':
        - UNLIMITED
  tenants:
    adm_tenant: RW
    test_tenant_ro: RW

# Read all and monitor, but no write permissions
sg_readonly_and_monitor:
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    '*':
      '*':
        - INDICES_ALL

# Read all, but no write permissions
sg_readall:
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    '*':
      '*':
        - READ

# For users which use kibana
sg_kibana:
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    '*':
      '*':
        - READ
    '?kibana':
      '*':
        - INDICES_ALL

# For the kibana server
sg_kibana_server:
  cluster:
      - CLUSTER_MONITOR
      - CLUSTER_COMPOSITE_OPS
      - cluster:admin/xpack/monitoring*
  indices:
    '?kibana*':
      '*':
        - INDICES_ALL

# For logstash and beats
sg_logstash:
  cluster:
    - indices:admin/template/get
    - indices:admin/template/put
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    'logstash-*':
      '*':
        - CRUD
        - CREATE_INDEX
    '*beat*':
      '*':
        - CRUD
        - CREATE_INDEX

# Allows each user to access own named index
sg_own_index:
  cluster:
    - CLUSTER_COMPOSITE_OPS
  indices:
    '${user_name}':
      '*':
        - INDICES_ALL

# Allows adding and modifying repositories
# and creating and restoring snapshots
sg_manage_snapshots:
  cluster:
    - MANAGE_SNAPSHOTS
  indices:
    '*':
      '*':
        - "indices:data/write/index"
        - "indices:admin/create"

# Make xpack monitoring work
sg_monitor:
  cluster:
    - cluster:admin/xpack/monitoring/*
    - cluster:admin/ingest/pipeline/put
    - cluster:admin/ingest/pipeline/get
    - indices:admin/template/get
    - indices:admin/template/put
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?monitor*':
      '*':
        - INDICES_ALL
    '?marvel*':
      '*':
        - INDICES_ALL
    '?kibana*':
      '*':
        - READ
    '*':
      '*':
        - indices:data/read/field_caps

# Make xpack alerting work
sg_alerting:
  cluster:
    - indices:data/read/scroll
    - cluster:admin/xpack/watcher/watch/put
    - cluster:admin/xpack/watcher*
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    '?kibana*':
      '*':
        - READ
    '?watches*':
      '*':
        - INDICES_ALL
    '?watcher-history-*':
      '*':
        - INDICES_ALL
    '?triggered_watches':
      '*':
        - INDICES_ALL
    '*':
      '*':
        - READ

# Examples
sg_role_starfleet:
  cluster:
    - CLUSTER_COMPOSITE_OPS
  indices:
    sf:
       ships:
         - READ
       public:
         - INDICES_ALL
       students:
         - READ
       alumni:
         - READ
    'pub*':
       '*':
         - READ
  tenants:
    enterprise_tenant: RW
    test_tenant_ro: RW

sg_role_starfleet_captains:
  indices:
    sf:
       '*':
         - CRUD
    pub*:
       '*':
         - CRUD
  cluster:
    - 'cluster:monitor*'
    - CLUSTER_COMPOSITE_OPS
  tenants:
    command_tenant: RW

sg_readonly_dlsfls:
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    '/\S*/':
      '*':
        - READ
      _dls_: '{"term" : {"_type" : "legends"}}'
      _fls_:
        - 'aaa'
        - 'bbb'

sg_kibana_testindex:
  cluster:
    - CLUSTER_COMPOSITE_OPS_RO
  indices:
    'test*':
      '*':
        - READ
        - indices:admin/mappings/fields/get*
    '?kibana':
      '*':
        - INDICES_ALL
  tenants:
    test_tenant_rw: RW
    test_tenant_ro: RO
```

sg_role_mapping (added david to admins)
```
# In this file users, backendroles and hosts can be mapped to search guard roles.
# What a role is allowed to do you specify in sg_roles.yml

sg_all_access:
  users:
    - admin
    - david

sg_logstash:
  users:
    - logstash

sg_kibana_server:
  users:
    - kibanaserver

sg_kibana:
  backendroles:
    - kibanarole

sg_monitor:
  backendroles:
    - kibanarole

sg_alerting:
  backendroles:
    - kibanarole

sg_public:
  users:
    - '*'

sg_readall:
  users:
    - readall

sg_own_index:
  users:
    - '*'

# Examples
sg_role_starfleet:
  backendroles:
    - starfleet
    - captains
    - defectors
    - 'cn=ldaprole,ou=groups,dc=example,dc=com'
  hosts:
    - "*.starfleetintranet.com"
  users:
    - worf
    - riker
    - troid

sg_role_starfleet_captains:
  backendroles:
    - captains

sg_role_klingons1:
  backendroles:
    - klingon
  hosts:
    - "*.klingongov.kli"
  users:
    - worf

sg_kibana_testindex:
  users:
    - test

sg_readonly_dlsfls:
  users:
    - dlsflsuser
```
