### ISSUE TITLE
Error start kibana:6.1.1 after install own home plugin

### ISSUE THREAD

**Issue by yunlzheng** [wtakase/kibana-own-home#68]
Thanks for your awesome kibana plugin. I have some issue in version 6.1.1

### Environment

* kibana-oss:6.1.1
* elasticsearch:6.1.1
* kibana-own-home:6.1.1

### Describe

I try to start the kibana in docker-compose:

```
  kibana:
    image: wisecity/kibana:6.1.1
    ports: 
    - 5601:5601
    depends_on:
    - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch
```

The image **wisecity/kibana:6.1.1** is build from **docker.elastic.co/kibana/kibana-oss:6.1.1** with kibana-own-home plugin.

after

```
docker-compose up -d
```
i get some error like follow:

```
{"type":"log","@timestamp":"2018-01-30T06:35:25Z","tags":["status","plugin:elasticsearch@6.1.1","info"],"pid":1,"state":"yellow","message":"Status changed from uninitialized to yellow - Waiting for Elasticsearch","prevState":"uninitialized","prevMsg":"uninitialized"}
/usr/share/kibana/plugins/own_home/server/proxy/init_proxy.js:161
      throw err;
      ^

Error: listen EADDRNOTAVAIL 172.22.0.2:9200
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at net.js:1408:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
```
